# -*- coding: utf-8 -*-
"""
get_val_accuracy.py

Get val accuracy from predictions dictionary generated by visualize_model_
predictions.py

Created on Thu Jul 21 11:56:20 2022

@author: linel
"""
import numpy as np
import pickle
import sys

def main(args : list):
    '''
    Get val accuracy from predictions dictionary generated by visualize_model_
    predictions.py

    Parameters
    ----------
    args : list
        command line args
        
        args[0] : name of script
        
        args[1] : predictions pickle file
        
        args[2] : file to print accuracy to

    Returns
    -------
    None.

    '''
    predictions = pickle.load(open(args[1], 'rb'))
    correct_predictions = 0
    samples = 0
    for prediction in predictions.values():
        predicted_labels = np.array(prediction['scores'])
        predicted_labels = predicted_labels > 0.5
        true_labels = np.array([prediction['label']]*predicted_labels.size)
        
        correct_predictions += (predicted_labels == true_labels).sum()
        samples += predicted_labels.size
        
    accuracy = correct_predictions/samples
    
    with open(args[2], 'a') as f:
        print(args[1] + '\t' + str(accuracy), file=f)
            
if __name__ == '__main__':
    main(sys.argv)